### PR TITLE
update pact-js library

### LINKED ISSUE #924: update pact-js library
our version of the pact-js library is pretty old, so it need to be updated. There are some breaking changes in the current version

### PR DESCRIPTION
**Pull request by individual-it**
fixes #924

- upgrade @pact-foundation/pact to 10.0.0-beta.59
- set contentType for requests

### CODE REVIEW

**Comment by individual-it** [comment]
currently blocked by https://github.com/pact-foundation/pact-reference/pull/186

**Comment by pascalwengerter** [comment]
> currently blocked by [pact-foundation/pact-reference#186](https://github.com/pact-foundation/pact-reference/pull/186)

@individual-it the linked PR has been merged, could you take care and update this one with a newer version? :)

**Comment by individual-it** [comment]
@pascalwengerter the PR is merged, but no new v10 release yet https://github.com/pact-foundation/pact-js/releases
I will ping the developers in their chat

**Comment by individual-it** [comment]
still no new release :zzz:

**Comment by individual-it** [comment]
new version was released today, I will have a look into this again next week

**Comment by individual-it** [comment]
there seems to be a new bug in the lib: multiple providerStates with the same name are not written into the contract JSON, see https://pact-foundation.slack.com/archives/C9VBGLUM9/p1649051146896539

**Comment by individual-it** [comment]
currently blocked by https://github.com/pact-foundation/pact-js/issues/848

**Comment by kulmann** [comment]
We'll archive the `owncloud-sdk` as soon as https://github.com/owncloud/web fully implements SharingNG. The `webdav` parts of the sdk are already unused in web. Not worth the time to follow up on this any further. Thank you for your efforts in making this work again!

**Pull request closed without merging**
