### PR TITLE
convert some of the user tests to pact.io

### PR DESCRIPTION
**Pull request by individual-it**
part of #500

### CODE REVIEW

**Comment by individual-it** [comment]
`Chromium 83.0.4103.61 (Ubuntu 0.0.0): Executed 36 of 257 (skipped 221) SUCCESS (15.127 secs / 6.03 secs)`

**Comment by individual-it** [comment]
I haven't converted the whole file to keep the PR small

**Review by swoichha — COMMENTED** [review]
LGTM

**Review by phil-davis — APPROVED** [review]
Looks good - just 1 text string

**Pull request merged**
