### PR TITLE
Do not skip ocis search results

### PR DESCRIPTION
**Pull request by aduffeck**

### CODE REVIEW

**Review by JanAckermann — APPROVED** [review]

**Comment by fschade** [comment]
@aduffeck can you please rebase master, this should make your pr pass

**Comment by individual-it** [comment]
I don't think that was rebased correctly, I cannot see the log output of https://github.com/owncloud/owncloud-sdk/blob/master/.drone.star#L73

**Comment by phil-davis** [comment]
https://github.com/aduffeck/owncloud-sdk/tree/ocis-search-results
"This branch is 1 commit ahead, 8 commits behind owncloud/owncloud-sdk:master."

Still needs to be rebased to current master.

**Comment by phil-davis** [comment]
The master of https://github.com/aduffeck/owncloud-sdk is out-of-date:
"This branch is 8 commits behind owncloud/owncloud-sdk:master."

@aduffeck you will need to pull latest master from "upstream" and rebase to that.

**Comment by aduffeck** [comment]
Thanks, rebase against master helped :+1:

**Review by fschade — APPROVED** [review]

**Pull request merged**
