### PR TITLE
[Tests-Only] move signedUrl, sharingWithAttributres and shareRecipientTest to jest and pactV3

### PR DESCRIPTION
**Pull request by dpakach**
move tests to jest
- signedUrl
- sharingWithAttributes
- shareReciepientTest
- signedUrlIntegrationTest
- XmlParserTest

part of #645 & #646

### CODE REVIEW

**Comment by dpakach** [comment]
We get some warnings while running tests now, courtesy of https://github.com/pact-foundation/pact-js/issues/397

**Review by individual-it — CHANGES_REQUESTED** [review]
the problem with https://github.com/pact-foundation/pact-js/issues/577 should be only in the resquest when using formdata, is there also a problem in the response?

**Review by jasson99 — COMMENTED** [review]
LGTM

**Comment by dpakach** [comment]
> the problem with [pact-foundation/pact-js#577](https://github.com/pact-foundation/pact-js/issues/577) should be only in the resquest when using formdata, is there also a problem in the response?

@individual-it that is existent in any string like body, so that error should occur on `text/plain` responses too

**Review by individual-it — APPROVED** [review]

**Pull request merged**
