### PR TITLE
bump pact to support arm64

### PR DESCRIPTION
**Pull request by fschade**
as title says, running tests on current master does not work for m1 macs.

Bildschirmfoto 2022-01-26 um 10 51 30

### CODE REVIEW

**Comment by kulmann** [comment]
Sooo this fixes https://github.com/owncloud/owncloud-sdk/issues/959 ? ;-) Why wasn't the upgrade considered before @JammingBen @individual-it - anything blocking this?

**Comment by pascalwengerter** [comment]
Duplicate of #961, comment by @individual-it [here](https://github.com/owncloud/owncloud-sdk/pull/961#issuecomment-1021064665)

**Comment by JammingBen** [comment]
We already have the same PR: https://github.com/owncloud/owncloud-sdk/pull/961 :)

Note the last comment, we're running into several issues here unfortunately...

**Comment by kulmann** [comment]
Ok, so it was considered before 😁 I'm closing this PR

**Pull request closed without merging**
